package stdmgmtapp;

import javax.swing.JFrame;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hp
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        welcome = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        studentscount = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        coursescount = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        managemenu = new javax.swing.JMenuItem();
        addmenu = new javax.swing.JMenuItem();
        EnrollStudentInCourse = new javax.swing.JMenuItem();
        Courses = new javax.swing.JMenu();
        addcourse = new javax.swing.JMenuItem();
        managecourses = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        addscore = new javax.swing.JMenuItem();
        editdelscore = new javax.swing.JMenuItem();
        showscores = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        AddAttendence = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        editattendence = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        welcome.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        welcome.setForeground(new java.awt.Color(102, 102, 102));
        welcome.setText("Welcome <####>");

        jPanel5.setBackground(new java.awt.Color(255, 255, 102));

        studentscount.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        studentscount.setText("Students Count=");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(studentscount, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addComponent(studentscount)
                .addGap(34, 34, 34))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 102));

        coursescount.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        coursescount.setText("Courses Count=");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(coursescount, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(coursescount)
                .addGap(37, 37, 37))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clg.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(welcome, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 350, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(welcome)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 210, Short.MAX_VALUE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(127, 127, 127))
        );

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/student.png"))); // NOI18N
        jMenu3.setText("Student");

        managemenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/managepeople.jpg"))); // NOI18N
        managemenu.setText("Manage");
        managemenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managemenuActionPerformed(evt);
            }
        });
        jMenu3.add(managemenu);

        addmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/addpeople.png"))); // NOI18N
        addmenu.setText("Add");
        addmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addmenuActionPerformed(evt);
            }
        });
        jMenu3.add(addmenu);

        EnrollStudentInCourse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/done.jpg"))); // NOI18N
        EnrollStudentInCourse.setText("EnrollStudentInCourse");
        EnrollStudentInCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnrollStudentInCourseActionPerformed(evt);
            }
        });
        jMenu3.add(EnrollStudentInCourse);

        jMenuBar1.add(jMenu3);

        Courses.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/courses.jpg"))); // NOI18N
        Courses.setText("Courses");

        addcourse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/course.jpg"))); // NOI18N
        addcourse.setText("Add Course");
        addcourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addcourseActionPerformed(evt);
            }
        });
        Courses.add(addcourse);

        managecourses.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/managecourses.png"))); // NOI18N
        managecourses.setText("Manage Courses");
        managecourses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managecoursesActionPerformed(evt);
            }
        });
        Courses.add(managecourses);

        jMenuBar1.add(Courses);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/score.jpg"))); // NOI18N
        jMenu1.setText("Score");

        addscore.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/addscore.png"))); // NOI18N
        addscore.setText("Add Score");
        addscore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addscoreActionPerformed(evt);
            }
        });
        jMenu1.add(addscore);

        editdelscore.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/editscore.jpg"))); // NOI18N
        editdelscore.setText("Edit/Delete Score");
        editdelscore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editdelscoreActionPerformed(evt);
            }
        });
        jMenu1.add(editdelscore);

        showscores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/showscores.png"))); // NOI18N
        showscores.setText("Show Scores");
        showscores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showscoresActionPerformed(evt);
            }
        });
        jMenu1.add(showscores);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/att.jpg"))); // NOI18N
        jMenu2.setText("Attendence");

        AddAttendence.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/addattt.png"))); // NOI18N
        AddAttendence.setText("Add Attendence");
        AddAttendence.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddAttendenceActionPerformed(evt);
            }
        });
        jMenu2.add(AddAttendence);

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/viewatt.png"))); // NOI18N
        jMenuItem3.setText("View Attendence");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        editattendence.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/editatt.png"))); // NOI18N
        editattendence.setText("Edit Attendence Records");
        editattendence.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editattendenceActionPerformed(evt);
            }
        });
        jMenu2.add(editattendence);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addmenuActionPerformed
        AddStudent mf=new AddStudent();
        mf.setVisible(true);
        mf.pack();
        mf.setLocationRelativeTo(null);
        mf.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_addmenuActionPerformed

    private void managemenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managemenuActionPerformed
        ManageStudentsForm mf=new ManageStudentsForm();
        mf.setVisible(true);
        mf.pack();
        mf.setLocationRelativeTo(null);// TODO add your handling code here:
        mf.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    
    }//GEN-LAST:event_managemenuActionPerformed

    private void addcourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addcourseActionPerformed
        AddCourse mf=new AddCourse();
        mf.setVisible(true);
        mf.pack();
        mf.setLocationRelativeTo(null);// TODO add your handling code here:
        mf.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    // TODO add your handling code here:
    }//GEN-LAST:event_addcourseActionPerformed

    private void managecoursesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managecoursesActionPerformed
        ManageCourses msf=new ManageCourses();
        msf.setVisible(true);
        msf.pack();
        msf.setLocationRelativeTo(null);
        msf.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_managecoursesActionPerformed

    private void addscoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addscoreActionPerformed
       AddScore msf=new AddScore();
        msf.setVisible(true);
        msf.pack();
        msf.setLocationRelativeTo(null);
        msf.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); // TODO add your handling code here:
    }//GEN-LAST:event_addscoreActionPerformed

    private void editdelscoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editdelscoreActionPerformed
editdeletescore msf=new editdeletescore();
        msf.setVisible(true);
        msf.pack();
        msf.setLocationRelativeTo(null);
        msf.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);        // TODO add your handling code here:
    }//GEN-LAST:event_editdelscoreActionPerformed

    private void showscoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showscoresActionPerformed
       showscores msf=new showscores();
        msf.setVisible(true);
        msf.pack();
        msf.setLocationRelativeTo(null);
        msf.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);  // TODO add your handling code here:
    }//GEN-LAST:event_showscoresActionPerformed

    private void EnrollStudentInCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnrollStudentInCourseActionPerformed
        EnrollStudentinCourse e=new EnrollStudentinCourse();
        e.setVisible(true);
        e.pack();
        e.setLocationRelativeTo(null);
        e.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); // TODO add your handling code here:
    }//GEN-LAST:event_EnrollStudentInCourseActionPerformed

    private void AddAttendenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddAttendenceActionPerformed
        AddAttendance msf=new AddAttendance();
        msf.setVisible(true);
        msf.pack();
        msf.setLocationRelativeTo(null);
        msf.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); 
    }//GEN-LAST:event_AddAttendenceActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        ShowAttendence msf=new ShowAttendence();
        msf.setVisible(true);
        msf.pack();
        msf.setLocationRelativeTo(null);
        msf.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);  // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void editattendenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editattendenceActionPerformed
        Editattendence msf=new Editattendence();
        msf.setVisible(true);
        msf.pack();
        msf.setLocationRelativeTo(null);
        msf.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);  // TODO add your handling code here:
    }//GEN-LAST:event_editattendenceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AddAttendence;
    private javax.swing.JMenu Courses;
    private javax.swing.JMenuItem EnrollStudentInCourse;
    private javax.swing.JMenuItem addcourse;
    private javax.swing.JMenuItem addmenu;
    private javax.swing.JMenuItem addscore;
    public static javax.swing.JLabel coursescount;
    private javax.swing.JMenuItem editattendence;
    private javax.swing.JMenuItem editdelscore;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JMenuItem managecourses;
    private javax.swing.JMenuItem managemenu;
    private javax.swing.JMenuItem showscores;
    public static javax.swing.JLabel studentscount;
    public static javax.swing.JLabel welcome;
    // End of variables declaration//GEN-END:variables
}
